name: Wii Nightly Build

on:
  push:
    paths:
      - Makefile_wii
      - source/scratch/**
      - source/sdl/**
      - gfx/wii/**
      - gfx/*
      - include/**
      - .github/workflows/nightly-wii.yml
      - Dockerfile.wii
    branches:
      - main
  workflow_dispatch:

jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Create `romfs` directory
        run: mkdir romfs
      - name: Build and Export
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.wii
          target: exporter
          outputs: type=local,dest=.
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Scratch Wii Nightly
          path: scratch-wii.zip
