on:
  push:
    paths:
      - Makefile_3ds
      - source/scratch/**
      - source/3ds/**
      - gfx/**
      - include/**
  pull_request:
    paths:
      - Makefile_3ds
      - source/scratch/**
      - source/3ds/**
      - gfx/**
      - include/**
  workflow_dispatch:

jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install DevkitPro
        run: |
          wget https://apt.devkitpro.org/devkitpro-pub.gpg
          echo "deb [signed-by=$(pwd)/devkitpro-pub.gpg] https://apt.devkitpro.org stable main" | sudo tee /etc/apt/sources.list.d/devkitpro.list
          sudo apt update -y
          sudo apt install -y devkitpro-pacman
          echo "DEVKITPRO=/opt/devkitpro" >> $GITHUB_ENV
          echo "DEVKITARM=/opt/devkitpro/devkitARM" >> $GITHUB_ENV
          echo "$DEVKITPRO/tools/bin" >> $GITHUB_PATH
      - name: Install Dependencies
        run: sudo dkp-pacman -Sy --noconfirm 3ds-dev
      - name: Build
        run: make
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Scratch 3DS Nightly
          path: Scratch-3DS.3dsx
