name: 3DS Nightly Build

on:
  push:
    paths:
      - Makefile_3ds
      - source/scratch/**
      - source/3ds/**
      - gfx/**
      - include/**
  pull_request:
    paths:
      - Makefile_3ds
      - source/scratch/**
      - source/3ds/**
      - gfx/**
      - include/**
  workflow_dispatch:

jobs:
  nightly:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitarm:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: sudo dkp-pacman -Sy --noconfirm 3ds-dev
      - name: Build
        run: make
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Scratch 3DS Nightly
          path: Scratch-3DS.3dsx
