name: Wii U Nightly Build

on:
  push:
    paths:
      - Makefile_wiiu
      - source/scratch/**
      - source/sdl/**
      - gfx/wiiu/**
      - include/**
      - .github/workflows/nightly-wiiu.yml
    branches:
      - main
  workflow_dispatch:

jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and Export
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.wiiu
          target: exporter
          outputs: type=local,dest=.
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Scratch Wii U Nightly
          path: scratch-wiiu/
